name: Build and Test FrontEnd React Application when Frontend files are edited

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**.js
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**.js

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 21.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd frontend
          npm ci
          npm run build --if-present
          npm test
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: joseche/reference-architecture/frontend
          registry: docker.pkg.github.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
          workdir: frontend
          dockerfile: Dockerfile
          tags: latest
        
