# workflow name
name: Test, Build Publish FrontEnd

# events
on:
  push:
    branches: [ main ]
    paths:
      - frontend/**.js
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**.js

# jobs
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
        # node-version: [18.x, 21.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd frontend
          npm ci
          npm run build --if-present
          npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: joseche/reference-architecture/frontend
          tags: 
            type=semver,pattern={{version}}
      - name: Docker Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: joseche/reference-architecture/frontend
          registry: ghcr.io
          # username: ${{ secrets.USERNAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          workdir: frontend
          tags: ${{ steps.meta.outputs.tags }}